---
book_repo: pivotal-cf/docs-book-antivirus
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-addon-antivirus
    ref: 'v1.2'
  directory: addon-antivirus
  subnav_template: addon_antivirus.erb