---
book_repo: pivotal-cf/docs-book-antivirus
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-addon-antivirus
    ref: '2.0'
  directory: addon-antivirus/2-0
  subnav_template: addon_antivirus_2-0.erb
  product_info:
    use_local_header: true
    latest_stable_version: 2.0
    changelog_href: https://docs.pivotal.io/addon-antivirus/2-0/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: ClamAV Add-on for PCF
    search_placeholder: Search ClamAV Add-on for PCF 2.0
    url_prefix: addon-antivirus/2-0
    local_product_version: 2.0
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-antivirus/1-4
        display_name: 1.4
      - <a href="http://docs.pivotal.io/archives/addon-antivirus-1.3.pdf">v1.3</a>
      - <a href="http://docs.pivotal.io/archives/addon-antivirus-1.2.pdf">v1.2</a>

- repository:
    name: pivotal-cf/docs-addon-antivirus
    ref: 'v1.4'
  directory: addon-antivirus/1-4
  subnav_template: addon_antivirus_1-4.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.4
    changelog_href: https://docs.pivotal.io/addon-antivirus/1-4/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: ClamAV Add-on for PCF
    search_placeholder: Search ClamAV Add-on for PCF 1.4
    url_prefix: addon-antivirus/1-4
    local_product_version: 1.4
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-antivirus/2-0
        display_name: ''
      - <a href="http://docs.pivotal.io/archives/addon-antivirus-1.3.pdf">v1.3</a>
      - <a href="http://docs.pivotal.io/archives/addon-antivirus-1.2.pdf">v1.2</a>
